#pragma once

#include "SpxBase.h"
#include "elements/SpxRigidBody.h"
#include "elements/SpxState.h"
#include "elements/SpxCollidable.h"
#include "elements/SpxShape.h"
#include "elements/SpxContact.h"
#include "elements/SpxConstraint.h"
#include "elements/SpxPair.h"
#include "elements/SpxBallJoint.h"
#include "elements/SpxConvexMesh.h"
#include "pipeline/SpxAllocator.h"
#include "pipeline/SpxBroadphase.h"
#include "pipeline/SpxCollisionDetection.h"
#include "pipeline/SpxConstraintSolver.h"
#include "pipeline/SpxIntegrate.h"
#include "pipeline/SpxSort.h"